before-cargo = []
cargo = ["cargo verify-project", "cargo check --all-targets --profile=test", "cargo deny check", "cargo audit", "cargo test -j 4 --no-fail-fast -- --show-output", "cargo fmt --check", "cargo clippy -- -D clippy::pedantic -W clippy::nursery -D warnings  -D clippy::all", "cargo outdated"]
after-cargo = []

[badge]
success = ["curl https://img.shields.io/badge/zuu-success-green -o zuu.svg"]
failure = ["curl https://img.shields.io/badge/zuu-failure-red -o zuu.svg"]